import { createProcessor } from "./markdown.js";

export async function renderReleaseBody({
  config,
  env,
  group,
  info,
  owner,
  repo,
  repos,
  setOutput,
  tag,
  tagBody,
}) {
  const parts = [];

  if (tagBody.trim() !== "") {
    const renderedTagBody = await group(
      "Rendering tag annotation body",
      async () => {
        const process = createProcessor({ owner, repo });
        const processed = await process(tagBody);

        return processed.trim();
      }
    );

    setOutput("tagBodyRendered", renderedTagBody);
    parts.push(renderedTagBody);
  }

  if (config.generateReleaseNotes) {
    const releaseNotes = await group(
      "Rendering automatically generated release notes",
      async () => {
        const {
          data: { body },
        } = await repos.generateReleaseNotes({ owner, repo, tag_name: tag });
        info(body);

        return body;
      }
    );

    setOutput("generatedReleaseNotes", releaseNotes);

    parts.push("", releaseNotes);
  }

  // GitHub renders unaccompanied HTML comments as plaintext, so skip the attribution
  if (parts.length < 1) return "";

  parts.unshift(`<!-- generated by ${env.GITHUB_ACTION_REPOSITORY} -->`);

  return parts.join("\n");
}
