name: Publish release (manual)

on:
  workflow_dispatch:
    inputs:
      tag:
        description: The tag to publish
        type: string
        required: true

jobs:
  publish:
    name: Ghalactic
    uses: ghalactic/repos/.github/workflows/shared-publish-release.yml@main
    secrets: inherit
    permissions:
      contents: write
      discussions: write
    with:
      discussionCategory: Releases
      useReleaseActionMain: true
      tag: ${{ inputs.tag }}
